services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker_net

  wordpress:
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    build: ./requirements/wordpress
    networks:
      - docker_net

  nginx:
    restart: always
    depends_on:
      - wordpress
    build:
      ./requirements/nginx
    volumes:
      - wordpress:/tmp/www/html
    ports:
      - "443:443"
    networks:
      - docker_net

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/requirements/mariadb/data
      o: bind,rw

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/requirements/wordpress/data
      o: bind,rw

networks:
  docker_net:
    driver: bridge