services:
  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker_net

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    build:
      context: ./requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    networks:
      - docker_net

  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        - CERT_KEY=${CERT_KEY}
        - CERT_CRT=${CERT_CRT}
    volumes:
        - wordpress:/var/www/html
    ports:
      - "443:443"
    expose:
      - "443"
    networks:
      - docker_net

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb/data
      o: bind,rw

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress/data
      o: bind,rw

networks:
  docker_net:
    driver: bridge