FROM alpine:3.19

RUN apk update && apk upgrade && \
	apk add --no-cache mariadb &&\
	apk add --no-cache mariadb-client

RUN mkdir -p /var/run/mysqld && \
	chmod 755 /var/run/mysqld && \
	chown -R mysql:mysql /var/run/mysqld && \
	chmod 777 /var/run/mysql

RUN mkdir -p /var/lib/mysql

COPY ./tools/50-server.cnf /etc/my.cnf
RUN chmod 777 /etc/my.cnf

COPY ./tools/execute_db.sh /execute_db.sh
RUN chmod +x /execute_db

EXPOSE 3306

RUN ./execute_db.sh && rm ./execute_db.sh

USER mysql

CMD [ "/usr/bin/mysqld", "--skip-log-error" ]