FROM alpine:3.19

RUN apk update && apk upgrade && \
	apk add --no-cache mariadb &&\
	apk add --no-cache mariadb-client

RUN mkdir -p /var/lib/mysql && \
	mkdir -p /run/mysqld && \
	chmod 755 /run/mysqld && \
	chown -R mysql:mysql /run/mysqld

COPY ./tools/50-server.cnf /etc/my.cnf

RUN chmod 644 /etc/my.cnf

RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY ./tools/execute_db.sh /execute_db.sh
RUN chmod +x /execute_db.sh

EXPOSE 3306

RUN ./execute_db.sh && rm ./execute_db.sh

USER mysql

CMD [ "/usr/bin/mysqld", "--user=mysql", "--skip-log-error" ]