FROM alpine:3.19

RUN apk update && \
	apk upgrade && \
	apk add --no-cache vsftpd

EXPOSE 21 21000-21010

COPY ./tools/vsftpd.conf /etc/vsftpd/vsftpd.conf
COPY ./tools/setup.sh /tmp/setup.sh

RUN chmod +x /tmp/setup.sh

ENTRYPOINT [ "/tmp/setup.sh" ]
CMD ["vsftpd", "/etc/vsftpd/vsftpd.conf"]