FROM alpine:3.19

EXPOSE 3306
EXPOSE 9000

RUN apk update && \
	apk upgrade && \
	apk add --no-cache \
			php82 \
			php82-fpm \
			php82-opcache \
			php82-mysqli \
			fcgi \
			php82-cgi \
			php82-phar

COPY ./tools/www.conf /etc/php82/php-fpm.d/www.conf

COPY ./tools/execute_wp.sh /tmp/execute_wp.sh

RUN addgroup -S wordpress && \
	adduser -S -G wordpress -H -s /sbin/nologin wordpress && \
	mkdir -p /var/www/html && \
	chown -R wordpress:wordpress /var/www/html

WORKDIR /var/www/html

RUN	wget https://wordpress.org/latest.zip && \
    unzip latest.zip && \
    cp -rf wordpress/* . && \
    rm -rf wordpress latest.zip

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /bin/wp

RUN chmod 777 /tmp/execute_wp.sh && \
	/bin/sh /tmp/execute_wp.sh && \
	rm /tmp/execute_wp.sh

USER wordpress


CMD [ "php-fpm82", "F"]
