FROM alpine:3.19

EXPOSE 3306

EXPOSE 9000

RUN apk update && \
	apk upgrade && \
	apk add --no-cache \
			php82 \
			php82-fpm \
			php82-opcache \
			php82-mysqli \
			fcgi \
			php82-cgi \
			php82-phar

RUN addgroup -S wordpress && \
	adduser -S -G wordpress -H -s /sbin/nologin wordpress && \
	mkdir -p /var/www/html/wordpress && \
	chown -R wordpress:wordpress /var/www/html

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /bin/wp

USER wordpress

RUN wp config create \
		--dbname=${MYSQL_DB_NAME} \
		--dbuser=${MYSQL_USER} \
		--dbpass=${MYSQL_DB_PASSWORD} \
		--dbhost=${MYSQL_DB_HOST} \
		--path=/var/www/html/wordpress \
		--skip-check

RUN cd /var/www/html/wordpress && \
	wp core install \
		--url=seongwol.42.kr \
		--title="inception" \
		--admin_user=seongwol \ 
		--admin_password=1234 \
		--admin_email=gbssw13@gmail.com \
		--locale=ko_KR && \
	wp user create evaluator@example.com \
		--user_pass=1234

CMD [ "php82-fpm" ]