FROM alpine:3.19

RUN apk update && \
	apk upgrade && \
	apk add --no-cache nginx && \
	mkdir -p /var/www/html/ && \
	mkdir -p /var/lib/nginx/var/run/ && \
	chmod -R 755 /var/www/html
	
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./srcs/ /var/www/html

RUN	chmod -R 755 /var/www/html && \
	chown -R nginx:nginx /var/www/html/ && \
	chown -R nginx:nginx /var/log/nginx /var/run/nginx && \
	chown -R nginx:nginx /var/lib/nginx/
	
EXPOSE 1234

CMD [ "nginx", "-g", "daemon off;" ]