FROM alpine:3.19

RUN apk update && \
	apk upgrade && \
	apk add --no-cache nginx && \
	mkdir -p /var/www/html && \
	chmod -R 755 /var/www/html && \
	chown -R nginx:nginx /var/www/html /var/log/nginx /var/run/nginx

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

RUN	mkdir -p /etc/nginx/ssl && \
	apk add --no-cache openssl && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
		-keyout /etc/nginx/ssl/seongwol.42.fr.key \
		-out /etc/nginx/ssl/seongwol.42.fr.crt \
		-subj "/C=KR/ST=Seoul/L=Gangnam-gu/O=42Ecole/OU=42Seoul/CN=seongwol.42.fr"

USER nginx

CMD [ "nginx", "-g", "daemon off;" ]